### ISSUE TITLE
The size of output volume is bigger than given shape

### ISSUE THREAD

**Issue by EvanYyf** [cgohlke/psf#1]
It seems that the output volume is larger in size than the given shape, which obeys 2*n -1 formula due to the mirror symmetry. What should I do if I want to output the point spread function volume that equals to the given shape? Thank you for your answer.

**Comment by cgohlke** [comment]
Tune `PSF.shape` and `psf.dims` to your needs. Use `PSF.volume()` to get a volumetric psf with all symmetries applied.
